name: Docker - Build and push latest

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "release-*" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example
  BUILD_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example:buildimage

jobs:
  build-latest:
    name: Build Block
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into the container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to the registry
        id: build
        env:
          APP_IMAGE_URI: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
        run: |
          chmod +x build.sh
          ./build.sh
          echo "image-uri=$APP_IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Built Successfully"
        shell: bash
